import type { Product } from './types';

// Este archivo ya no es la fuente principal de datos, 
// pero se puede mantener como referencia o para pruebas iniciales.
// La aplicación ahora carga los productos desde Firebase.

export const products: Product[] = [
  {
    id: '1',
    name: 'Chaqueta de Mezclilla Clásica',
    description: 'Una chaqueta de mezclilla atemporal que es imprescindible en cualquier guardarropa. Perfecta para usar en capas en cualquier temporada.',
    price: 89.99,
    images: [
      'https://placehold.co/600x800.png',
      'https://placehold.co/600x800.png',
      'https://placehold.co/600x800.png',
    ],
    category: 'Caballeros',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Azul Clásico', hex: '#3B82F6' },
      { name: 'Negro', hex: '#000000' },
    ],
    rating: 4.5,
    stock: 100,
  },
  {
    id: '2',
    name: 'Vestido Maxi Fluido',
    description: 'Un vestido maxi elegante y cómodo con un estampado floral, perfecto para los días de verano u ocasiones especiales.',
    price: 120.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Damas',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Coral Atardecer', hex: '#FF7F50' },
      { name: 'Verde Azulado Océano', hex: '#2DD4BF' },
    ],
    rating: 4.8,
    stock: 75,
  },
  {
    id: '3',
    name: 'Camisa de Lino con Botones',
    description: 'Una camisa de lino transpirable y elegante, ideal para climas cálidos. Se puede vestir formal o informal.',
    price: 65.5,
    images: ['https://placehold.co/600x800.png'],
    category: 'Caballeros',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Blanco', hex: '#FFFFFF' },
      { name: 'Beige', hex: '#F5F5DC' },
    ],
    rating: 4.2,
    stock: 120,
  },
  {
    id: '4',
    name: 'Jeans Ajustados de Cintura Alta',
    description: 'Jeans ajustados de cintura alta que favorecen la figura y brindan comodidad y estilo. Un básico versátil para el guardarropa.',
    price: 75.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Damas',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Lavado Oscuro', hex: '#1E3A8A' },
      { name: 'Lavado Claro', hex: '#93C5FD' },
    ],
    rating: 4.6,
    stock: 80,
  },
  {
    id: '5',
    name: 'Chinos de Corte Entallado',
    description: 'Chinos modernos de corte entallado que ofrecen un aspecto casual e inteligente. Hechos de cómodo algodón elástico.',
    price: 70.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Caballeros',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Caqui', hex: '#C3B091' },
      { name: 'Azul Marino', hex: '#000080' },
    ],
    rating: 4.4,
    stock: 90,
  },
  {
    id: '6',
    name: 'Suéter de Punto Acogedor',
    description: 'Un suéter de punto suave y acogedor, perfecto para las tardes frescas. Presenta un clásico patrón de punto de ochos.',
    price: 95.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Damas',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Crema', hex: '#FFFDD0' },
      { name: 'Gris Jaspeado', hex: '#D1D5DB' },
    ],
    rating: 4.9,
    stock: 60,
  },
  {
    id: '7',
    name: 'Camiseta con Gráfico',
    description: 'Una cómoda camiseta de algodón con un estampado gráfico único. Perfecta para un look casual y expresivo.',
    price: 35.0,
    images: ['https://placehold.co/600x800.png'],
    category: 'Caballeros',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Blanco', hex: '#FFFFFF' },
      { name: 'Carbón', hex: '#36454F' },
    ],
    rating: 4.1,
    stock: 150,
  },
  {
    id: '8',
    name: 'Blusa de Mezcla de Seda',
    description: 'Una lujosa blusa de mezcla de seda con una hermosa caída. Perfecta para la oficina o una salida nocturna elegante.',
    price: 110.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Damas',
    sizes: ['XS', 'S', 'M'],
    colors: [
      { name: 'Champán', hex: '#F7E7CE' },
      { name: 'Esmeralda', hex: '#50C878' },
    ],
    rating: 4.7,
    stock: 50,
  },
];
