import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Denim Jacket',
    description: 'A timeless denim jacket that is a must-have for any wardrobe. Perfect for layering in any season.',
    price: 89.99,
    images: [
      'https://placehold.co/600x800.png',
      'https://placehold.co/600x800.png',
      'https://placehold.co/600x800.png',
    ],
    category: 'Men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Classic Blue', hex: '#3B82F6' },
      { name: 'Black', hex: '#000000' },
    ],
    rating: 4.5,
  },
  {
    id: '2',
    name: 'Flowy Maxi Dress',
    description: 'An elegant and comfortable maxi dress with a floral pattern, perfect for summer days or special occasions.',
    price: 120.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Women',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Sunset Coral', hex: '#FF7F50' },
      { name: 'Ocean Teal', hex: '#2DD4BF' },
    ],
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Linen Button-Up Shirt',
    description: 'A breathable and stylish linen shirt, ideal for warm weather. Can be dressed up or down.',
    price: 65.5,
    images: ['https://placehold.co/600x800.png'],
    category: 'Men',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Beige', hex: '#F5F5DC' },
    ],
    rating: 4.2,
  },
  {
    id: '4',
    name: 'High-Waisted Skinny Jeans',
    description: 'Flattering high-waisted skinny jeans that provide both comfort and style. A versatile wardrobe staple.',
    price: 75.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Women',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Dark Wash', hex: '#1E3A8A' },
      { name: 'Light Wash', hex: '#93C5FD' },
    ],
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Slim-Fit Chinos',
    description: 'Modern slim-fit chinos that offer a smart-casual look. Made from comfortable stretch cotton.',
    price: 70.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Navy', hex: '#000080' },
    ],
    rating: 4.4,
  },
  {
    id: '6',
    name: 'Cozy Knit Sweater',
    description: 'A soft and cozy knit sweater perfect for chilly evenings. Features a classic cable-knit pattern.',
    price: 95.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Women',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Cream', hex: '#FFFDD0' },
      { name: 'Heather Grey', hex: '#D1D5DB' },
    ],
    rating: 4.9,
  },
  {
    id: '7',
    name: 'Graphic T-Shirt',
    description: 'A comfortable cotton t-shirt with a unique graphic print. Perfect for a casual, expressive look.',
    price: 35.0,
    images: ['https://placehold.co/600x800.png'],
    category: 'Men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Charcoal', hex: '#36454F' },
    ],
    rating: 4.1,
  },
  {
    id: '8',
    name: 'Silk-Blend Blouse',
    description: 'A luxurious silk-blend blouse with a beautiful drape. Perfect for office wear or a chic evening out.',
    price: 110.0,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Women',
    sizes: ['XS', 'S', 'M'],
    colors: [
      { name: 'Champagne', hex: '#F7E7CE' },
      { name: 'Emerald', hex: '#50C878' },
    ],
    rating: 4.7,
  },
];
